package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for projectonto kernel
var projectonto_code cu.Function

// Stores the arguments for projectonto kernel invocation
type projectonto_args_t struct {
	arg_dstx unsafe.Pointer
	arg_dsty unsafe.Pointer
	arg_dstz unsafe.Pointer
	arg_ax   unsafe.Pointer
	arg_ay   unsafe.Pointer
	arg_az   unsafe.Pointer
	arg_bx   unsafe.Pointer
	arg_by   unsafe.Pointer
	arg_bz   unsafe.Pointer
	arg_N    int
	argptr   [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for projectonto kernel invocation
var projectonto_args projectonto_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	projectonto_args.argptr[0] = unsafe.Pointer(&projectonto_args.arg_dstx)
	projectonto_args.argptr[1] = unsafe.Pointer(&projectonto_args.arg_dsty)
	projectonto_args.argptr[2] = unsafe.Pointer(&projectonto_args.arg_dstz)
	projectonto_args.argptr[3] = unsafe.Pointer(&projectonto_args.arg_ax)
	projectonto_args.argptr[4] = unsafe.Pointer(&projectonto_args.arg_ay)
	projectonto_args.argptr[5] = unsafe.Pointer(&projectonto_args.arg_az)
	projectonto_args.argptr[6] = unsafe.Pointer(&projectonto_args.arg_bx)
	projectonto_args.argptr[7] = unsafe.Pointer(&projectonto_args.arg_by)
	projectonto_args.argptr[8] = unsafe.Pointer(&projectonto_args.arg_bz)
	projectonto_args.argptr[9] = unsafe.Pointer(&projectonto_args.arg_N)
}

// Wrapper for projectonto CUDA kernel, asynchronous.
func k_projectonto_async(dstx unsafe.Pointer, dsty unsafe.Pointer, dstz unsafe.Pointer, ax unsafe.Pointer, ay unsafe.Pointer, az unsafe.Pointer, bx unsafe.Pointer, by unsafe.Pointer, bz unsafe.Pointer, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("projectonto")
	}

	projectonto_args.Lock()
	defer projectonto_args.Unlock()

	if projectonto_code == 0 {
		projectonto_code = fatbinLoad(projectonto_map, "projectonto")
	}

	projectonto_args.arg_dstx = dstx
	projectonto_args.arg_dsty = dsty
	projectonto_args.arg_dstz = dstz
	projectonto_args.arg_ax = ax
	projectonto_args.arg_ay = ay
	projectonto_args.arg_az = az
	projectonto_args.arg_bx = bx
	projectonto_args.arg_by = by
	projectonto_args.arg_bz = bz
	projectonto_args.arg_N = N

	args := projectonto_args.argptr[:]
	cu.LaunchKernel(projectonto_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("projectonto")
	}
}

// maps compute capability on PTX code for projectonto kernel.
var projectonto_map = map[int]string{0: "",
	50: projectonto_ptx_50}

// projectonto PTX code for various compute capabilities.
const (
	projectonto_ptx_50 = `
.version 8.0
.target sm_50
.address_size 64

	// .globl	projectonto

.visible .entry projectonto(
	.param .u64 projectonto_param_0,
	.param .u64 projectonto_param_1,
	.param .u64 projectonto_param_2,
	.param .u64 projectonto_param_3,
	.param .u64 projectonto_param_4,
	.param .u64 projectonto_param_5,
	.param .u64 projectonto_param_6,
	.param .u64 projectonto_param_7,
	.param .u64 projectonto_param_8,
	.param .u32 projectonto_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [projectonto_param_0];
	ld.param.u64 	%rd2, [projectonto_param_1];
	ld.param.u64 	%rd3, [projectonto_param_2];
	ld.param.u64 	%rd4, [projectonto_param_3];
	ld.param.u64 	%rd5, [projectonto_param_4];
	ld.param.u64 	%rd6, [projectonto_param_5];
	ld.param.u64 	%rd7, [projectonto_param_6];
	ld.param.u64 	%rd8, [projectonto_param_7];
	ld.param.u64 	%rd9, [projectonto_param_8];
	ld.param.u32 	%r2, [projectonto_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd11;
	cvta.to.global.u64 	%rd15, %rd6;
	add.s64 	%rd16, %rd15, %rd11;
	cvta.to.global.u64 	%rd17, %rd7;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd11;
	ld.global.nc.f32 	%f1, [%rd18];
	ld.global.nc.f32 	%f2, [%rd12];
	ld.global.nc.f32 	%f3, [%rd20];
	ld.global.nc.f32 	%f4, [%rd14];
	mul.f32 	%f5, %f4, %f3;
	fma.rn.f32 	%f6, %f2, %f1, %f5;
	ld.global.nc.f32 	%f7, [%rd22];
	ld.global.nc.f32 	%f8, [%rd16];
	fma.rn.f32 	%f9, %f8, %f7, %f6;
	mul.f32 	%f10, %f1, %f9;
	mul.f32 	%f11, %f3, %f9;
	mul.f32 	%f12, %f7, %f9;
	cvta.to.global.u64 	%rd23, %rd1;
	add.s64 	%rd24, %rd23, %rd11;
	st.global.f32 	[%rd24], %f10;
	cvta.to.global.u64 	%rd25, %rd2;
	add.s64 	%rd26, %rd25, %rd11;
	st.global.f32 	[%rd26], %f11;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f12;

$L__BB0_2:
	ret;

}

`
)
